### ISSUE TITLE
User Story: Design Home Page Layout and Requirements

### ISSUE THREAD

**Issue by mbuturuga** [Dobbi-UDL/Dobbi-Project#73]
### Description
As a dev,
I want to design the layout of the web application pages
so that we know what components are needed and how they should be arranged.

### Acceptance Criteria
- Layout design is completed for Homepage 

### Dependencies
- #72

**Comment by ericlopezsegui** [comment]
![Image](https://github.com/user-attachments/assets/2bb8aeed-15e0-4656-b35a-3b099df6eaa7)
